// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { config } from "dotenv";
 
config();
const { DATABASE_URL } = process.env;
 
export default defineConfig({
  schema: "prisma/db-business/schema.prisma",
  migrations: {
    path: "prisma/db-business/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
